version: '3'

services:
   database:
      image: mongo:latest
      container_name: template_database
      ports:
         - 27017:27017
      expose:
         - 27017
      volumes:
         - template_data:/data/db
   api:
      image: template/api
      container_name: template_api
      build: .
      depends_on:
         - database
      ports:
         - 8080:8080

volumes:
   template_data:
